### ISSUE TITLE
Another seperator

### ISSUE THREAD

**Issue by michaelVoelker** [SeeSharpSoft/intellij-csv-validator#1]
Could  you add a configuration item for another seperator? In my case a semicolon is needed.

**Comment by SeeSharpSoft** [comment]
Formatter option to choose between Comma and Semicolon as separator implemented in 82491c18a5fdfeea5f8eba1fcc7f211633a3f1b9

Note: Providing an option for a free-text separator is not feasible without unreasonable huge effort. Other pre-defined separators can be added quite easily.
Said this, the tab character (\t) was also suggested but is treated like a white space by the SDK SpacingBuilder - spacing options ("Tabularize" makes also use of spacing) would not work.

**Comment by SeeSharpSoft** [comment]
@michaelVoelker: Plugin will probably be updated sometime next week in JetBrains repository, I currently have another update pending there and also need some time to finalize tests.
Feel free to give it a try via manual installation: https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.0-RC1

**Comment by SeeSharpSoft** [comment]
Included in Release 1.0
