### ISSUE TITLE
Adding column Version 2.2.1 is very slow

### ISSUE THREAD

**Issue by mjhopkins** [SeeSharpSoft/intellij-csv-validator#101]
I have a CSV with 3 rows, 15 columns. Trying to add a new column works, but there's a delay of a minute or two. In previous versions this was pretty snappy. After this, tables don't display properly, and IntelliJ is slow and unresponsive. I find I need to exit and restart to get back to normal.

**Comment by SeeSharpSoft** [comment]
This sounds very concerning - can you provide a sample CSV? Furthermore the used IntelliJ IDE (e.g. IDEA, PyCharm, etc.) and version might be helpful.

I tried to reproduce it but with even e.g. 10 rows and 30 columns I did not notice any performance issues.

**Comment by SeeSharpSoft** [comment]
Closing this due to no response and v2.3.1 already released
