### ISSUE TITLE
Scratches are not recognised as CSV

### ISSUE THREAD

**Issue by juandelacruz-calvo** [SeeSharpSoft/intellij-csv-validator#104]
I think the plugin works like a charm and it is really useful, the only but I can find is that Scratches are not automatically opened as CSV, also an option to create a CSV scratch would be amazing. 

Thanks! Good work!

**Comment by SeeSharpSoft** [comment]
@juandelacruz-calvo Thanks for your feedback - and for pointing this out! Until your comment I wasn't even aware of the "Scratch" feature - seems to be quite handy. I will investigate why the table editor is not available here, but the CSV text editor is in place and it is also possible to create a CSV scratch. Did I miss something?

![image](https://user-images.githubusercontent.com/3205800/53259284-0023ff00-36cf-11e9-9df8-46a3a4c8494f.png)
