### ISSUE TITLE
Not working pipe separator

### ISSUE THREAD

**Issue by manso92** [SeeSharpSoft/intellij-csv-validator#105]
Using pipes as separator it puts it together on table view

**Comment by manso92** [comment]
![image](https://user-images.githubusercontent.com/2530727/53167305-dcca5880-35d7-11e9-83f6-a639bd8276ee.png)

**Comment by SeeSharpSoft** [comment]
Did you change the separator for your project in the [formatter settings](https://github.com/SeeSharpSoft/intellij-csv-validator#formatting) to '|'?

**Comment by manso92** [comment]
Yes, it's set to it but it's no matching with any in the file

**Comment by manso92** [comment]
I'm trying to detect the error from myself, I'll write if I detect anything

**Comment by SeeSharpSoft** [comment]
@manso92 Did you find whats causing it? Can you provide an example file?

**Comment by ITSecMedia** [comment]
Tried this plugin in Rider and it doesn't get any other separator than Comma, why isn't there an ordinary dropdown box in the table editor menu next to the header settings where we can pick our custom defined Formats in the options (CSV formats) . There is no menu, nothing, where I can simply select which format I want to apply to an opened document ?

**Comment by SeeSharpSoft** [comment]
@ITSecMedia Please read the section about the  [https://github.com/SeeSharpSoft/intellij-csv-validator#formatting](separator settings).

File based separator settings are currently in development (#126).

> why isn't there an ordinary dropdown box in the table editor menu next to the header settings where we can pick our custom defined Formats in the options (CSV formats)

Cause nobody contributed it yet to this private open source project. 😕

**Comment by SeeSharpSoft** [comment]
With the new "CSV value separator" (`>= 2.4.0`) action it is possible now to define it file specific - `|` is one of the available separators.
