### ISSUE TITLE
New separator '|'

### ISSUE THREAD

**Issue by dgur1n** [SeeSharpSoft/intellij-csv-validator#11]
Could you add pipe symbol as separator? 
Thanks!

**Comment by SeeSharpSoft** [comment]
@dgur1n Yes, thats actually a quite useful one - just created a branch for the change (044e90803af9fe352dafb4672ffa06bf6fb44e4c)

I also want to add tabs as separator, which is still not working completely - I don't know what causes the issues described here (#5) but I want to take some time to invest in it. I will draft a new release later next week that will definitely include the | as separator.

**Comment by SeeSharpSoft** [comment]
Part of [Release 1.6.1](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.6.1)
