### ISSUE TITLE
Feature: Autosize columns on first file open

### ISSUE THREAD

**Issue by Sporking** [SeeSharpSoft/intellij-csv-validator#112]
The column sizes that the table editor currently chooses are far too short for my data (certain columns contain strings up to 60 characters long), and I get tired of having to manually resize the columns every time I open a file. (Also, some columns contain data that is too short for the default column headers, which wastes space. I have to resize these too in order to have enough space to display the wider columns.)

A feature request: When I open a new CSV file, I would like the table editor to do a scan of the file, determine the maximum length of each column, and autosize each table column accordingly. I would also like to be able to set a "maximum automatic column size" preference, so that the autosizing would not create columns larger than this preference value.

Ideally, the table editor would remember the column sizes that I used for a file (at least if any column widths were manually adjusted), for at least a while (the last N files I edited?) so that if I later reopened that file, the same column widths would be used and I wouldn't need to perform manual adjustments again.

**Comment by SeeSharpSoft** [comment]
Thanks for your suggestions. I will think about the autosize column feature in more detail - my biggest concern is that the performance impact for larger files might be quite noticable. An action/command to manually trigger an automatic column sizing might be a good alternative.

> Ideally, the table editor would remember the column sizes that I used for a file (at least if any column widths were manually adjusted), for at least a while (the last N files I edited?) so that if I later reopened that file, the same column widths would be used and I wouldn't need to perform manual adjustments again.

The feature of storing the widths of the columns per file is actually implemented and working fine for me - can you please double check?

**Comment by friederschueler** [comment]
I have exactly the same requirement as @Sporking: I need to automatically adjust all columns sizes to the maximum width of the content (doesn't matter if header or content colulmn) on first open. Then if I adjust columns manually I want to the editor to keep the changes stored.

I can help with an implementation if you want me to. If you give me a hint, where and how you want this to be implemented then I will try it and provide a PR

**Comment by SeeSharpSoft** [comment]
Thanks @friederschueler for offering help on this, but it is not much of an implementation effort but a conceptional one (that’s why I didn’t mark it as).

But first things first: 
> if I adjust columns manually I want to the editor to keep the changes stored

As mentioned before, this feature is implemented and was available from the very beginning. If it is not working, please let me know or open separate issue.


Now for the concept: What do you think is the general/usual expectation to auto-calculate the column widths? IMO it is not the maximum width of the content of each column, but a relative width of each column with respect to the largest one (and having a global maxWidth defined). What kind of settings should be provided to the user?

Furthermore, if column widths are auto adjusted and getting much larger than expected, me as a user also want to have an action to reset all columns back to the default width. So this feature must come at the same time (quite easy to implement though).

Additionally, I do not see this feature mandatory when opening a file - or at least not by default -, cause:
- it lowers performance on large files
- it is not always wanted, e.g. if one or more columns contain full texts
- it is not only wanted at first opening but also after some changes happened, so this feature should be a trigger-able action (also or only?)

Lets work together and ideate first to get the concept and UX straight before doing any implementation work - this last step will then be the easiest.

**Comment by friederschueler** [comment]
Thank you so much and sorry that I could not provide any more help (workload is high atm).
All my use-cases are working :)

**Comment by SeeSharpSoft** [comment]
Thanks for the feedback - glad to hear!
