### ISSUE TITLE
[question] Highlight value in row 2 column 3

### ISSUE THREAD

**Issue by ptahchiev** [SeeSharpSoft/intellij-csv-validator#120]
Hello @SeeSharpSoft,

first of all thank you for your great work. This is not really an issue but more a question. I'm developing a plugin that extends your plugin and at some point I want to highlight the value in row 2 column 3 (for example) as invalid. I'm stuck and I would really appreciate some help. Can you please guide me where to look, or provide me with a code snippet of how to do this.
Thank you again.

**Comment by SeeSharpSoft** [comment]
Thanks @ptahchiev!

What you need is most likely an [annotator](https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/annotator.html). I did write one [annotator for the CSV plugin](https://github.com/SeeSharpSoft/intellij-csv-validator/blob/master/src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvAnnotator.java) which is doing the balloon tooltips and the column based highlighting at once. You should definitely have a look there.

The reason to put both functions into one annotator class is performance. Take care, cause the `annotate` function is called fairly often - for each element and with every change.

**Column/Row information**: I do store the structure data of each CSV file. You can access it like in line 42 of the referenced annotator class:

```CsvColumnInfo<PsiElement> columnInfo = csvFile.getMyColumnInfoMap().getColumnInfo(element);```

With the help of the [CsvColumnInfoMap](https://github.com/SeeSharpSoft/intellij-csv-validator/blob/master/src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvColumnInfoMap.java)/[CsvColumnInfo](https://github.com/SeeSharpSoft/intellij-csv-validator/blob/master/src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvColumnInfo.java) you can retrieve additional context information like the row/column-index of the current element, e.g. `columnInfo.getColumnIndex()` or `columnInfo.getRowInfo(element).getRowIndex()`.

Hope this helps - happy hacking!
