### ISSUE TITLE
How to change separator in csv file?

### ISSUE THREAD

**Issue by Quipex** [SeeSharpSoft/intellij-csv-validator#121]
What if i accidentally have chosen the wrong separator, how to change it to another one in table editor?

**Comment by SeeSharpSoft** [comment]
https://github.com/SeeSharpSoft/intellij-csv-validator#separator-1

It sounds like you are asking about the - not CSV Plugin related - "Edit as table..." feature though...

**Comment by Quipex** [comment]
That link that you've had provided has solved the issue, thanks!

**Comment by Quipex** [comment]
I've wrote that i "have chosen a separator in your plugin" by mistake. The thing is I've used Google's Spreadsheets and it asks what type of separator I would like to define. Theese two have messed up my thoughts a bit 😅 
So "choosing separator" that i've mentioned before is not related to your plugin.
