### ISSUE TITLE
Some characters not represented properly in table editor/tooltip popover

### ISSUE THREAD

**Issue by zhanzufen** [SeeSharpSoft/intellij-csv-validator#122]
The chinese char with utf-8 encoding can not display correctly.

**Comment by SeeSharpSoft** [comment]
Can you provide an example (file) please. Thanks!

**Comment by SeeSharpSoft** [comment]
The plugin does use the common text editor, it does not come with any custom charset handling. The issue must most likely be addressed at Jetbrains IntelliJ platform.

**Comment by imlison** [comment]
doesn't work with chinese

>
 id,age,name
1,18,Lison
2,20,中文

**Comment by SeeSharpSoft** [comment]
What do you mean by "doesn't work with chinese"? For me it "works":

![image](https://user-images.githubusercontent.com/3205800/61320454-bb2d7000-a809-11e9-8cd7-aabed7f5eeb6.png)
![image](https://user-images.githubusercontent.com/3205800/61320333-81f50000-a809-11e9-9778-b30df0d26dc7.png)

**Comment by andryr** [comment]
I work with a file that contains chinese, japanese, korean and thai characters. In text mode there is no issue but in Table mode only japanese and chinese characters are displayed correctly
![screen_1](https://user-images.githubusercontent.com/6563044/63228974-5e9fe500-c1fb-11e9-8435-0beeaeaa203f.png)
![screen_2](https://user-images.githubusercontent.com/6563044/63228977-6069a880-c1fb-11e9-88cf-540712d088fe.png)

**Comment by SeeSharpSoft** [comment]
@andryr Thanks for providing this example file - I can reproduce the issue.

After investigating into #145, I guess this is most likely also an issue with the used font, not the encoding. Even the tooltip popover in text editor mode does not represent the characters properly.

**Comment by SeeSharpSoft** [comment]
There seems to be some general issues with Thai/Korean font within the IDE.

https://youtrack.jetbrains.com/issue/IDEA-203774
https://youtrack.jetbrains.com/issue/IDEA-220675
https://youtrack.jetbrains.com/issue/IDEA-221349

I hope to get some insights from those issues...

**Comment by SeeSharpSoft** [comment]
Info: for tooltip popover, the general appearance font needs to be adjusted (https://youtrack.jetbrains.com/issue/IDEA-221349)

**Comment by SeeSharpSoft** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004945020-Custom-editor-font-issues-Thai-Korean-language-

**Comment by SeeSharpSoft** [comment]
Upcoming release 2.8.0 comes with an advanced font-handling adjusting the font per cell in the table editor.
