### ISSUE TITLE
Enhancement: New separator ';'

### ISSUE THREAD

**Issue by isananic** [SeeSharpSoft/intellij-csv-validator#123]
Could you add the new separator ';', or even better create an option to define a custom separator?

**Comment by SeeSharpSoft** [comment]
';' already exists as an separator (see [Doku](https://github.com/SeeSharpSoft/intellij-csv-validator#separator-1))

A custom separator introduces many corner cases (e.g. **"** as a separator), very error prone and IMO not worth the effort (see [FAQ](https://github.com/SeeSharpSoft/intellij-csv-validator#faq))

**Comment by SeeSharpSoft** [comment]
With the new "CSV value separator" (`>= 2.4.0`) action it is possible now to define it file specific - `;` is one of the available separators.
