### ISSUE TITLE
Read only mode for Table editor or less aggressive

### ISSUE THREAD

**Issue by JodliDev** [SeeSharpSoft/intellij-csv-validator#124]
Thanks for this plugin!
I only have one issue:

I am mostly using the Table Editor to make sure, that automatically generated files have the correct structure. The problem is, that just by opening the Table Editor the original file is rewritten in the plugins format.
Because of that, I risk changing the originally created structure just by viewing the data in a table format. This means that I will not see minor mistakes in formatting which were automatically corrected. It also corrects empty lines and I always have to check the settings to make sure that the Table Editor is using exactly the same format that I am using in the current project.

It would be very helpful if the editor just has a "save"-option and leaves the original file untouched until that button is pressed.
Or having a "readonly"-mode where the editor just does not change the file at all

Thank you very much
Jodli

**Comment by SeeSharpSoft** [comment]
A somewhat related issue was raised some time ago, I wrote some details about the table editor vs text editor data handling (#110).

I will think about how to improve the "has-file-changed-check" and/or the introduction of a read-only mode.
