### ISSUE TITLE
The plugins breaks on the JSON data types.

### ISSUE THREAD

**Issue by Anruin** [SeeSharpSoft/intellij-csv-validator#135]
I export PostgreSQL table containing JSON data type columns. Opening it in the editor leads to errors as you can see on the attached screenshot. This single quote symbol from the JSON breaks the whole document which is huge.
![Screenshot from 2019-06-09 13-18-39](https://user-images.githubusercontent.com/1710308/59157759-207a9c80-8ab9-11e9-9548-d4e7dbbd7541.png)

**Comment by SeeSharpSoft** [comment]
Actually the plugin points out incorrect CSV syntax correctly (see similar issue #9).

If you are using the Jetbrains export functionality, please raise your voice via already existing (but unfortunately ignored) bug reports (https://youtrack.jetbrains.com/issue/DBE-5082, https://youtrack.jetbrains.net/issue/DBE-7217) or open a new one. The CSV format of the export is plain incorrect/erroneous and needs to be fixed.

Meanwhile you can mark the file via context menu as text-file to suppress the use of the CSV plugin for those files. Or you fix the incorrect syntax though 😞
