### ISSUE TITLE
No fallback font used in table editor

### ISSUE THREAD

**Issue by zsnjuts** [SeeSharpSoft/intellij-csv-validator#145]
It seems that it only supports UTF-8 and when I open a file with other encodings, words become squares, as is shown below. Is it possible to support document encoding change manually ?
![image](https://user-images.githubusercontent.com/16850617/62406213-a3603500-b5da-11e9-8f3d-7ef75d2b7713.png)

**Comment by SeeSharpSoft** [comment]
@zsnjuts Thanks for reporting. Can you provide a (simple) sample file?

Furthermore, how does it look in the text editor? Do you know about the file encoding switch there...
![image](https://user-images.githubusercontent.com/3205800/62408268-730e9b80-b5c6-11e9-9edb-35ab6203f405.png)

If you switch the used file encoding there, does it change sth in the table editor?

**Comment by zsnjuts** [comment]
I have chosen the right encoding GBK in `Text`, but in `Table Editor` words still are squares.
In `Text`:
![image](https://user-images.githubusercontent.com/16850617/62408668-d4526100-b5fe-11e9-8602-680d333f964e.png)
In `Table Editor`:
![image](https://user-images.githubusercontent.com/16850617/62408674-ee8c3f00-b5fe-11e9-97a6-95d516c396f5.png)

**Comment by SeeSharpSoft** [comment]
Thanks for providing the information and the sample file. I will investigate when I got some more time - a quick first look didn't give me any enlightening insights on how IntelliJ handles the file encoding.

**Comment by SeeSharpSoft** [comment]
https://youtrack.jetbrains.com/issue/IDEA-219307#focus=streamItem-27-3646303.0-0

@zsnjuts If you change the (default) editor font to "Monospaced" and re-open any CSV file, does it resolve the issue?

**Comment by zsnjuts** [comment]
Yes, it does. So it is the font that causes the problem, not the encoding. 😂
