### ISSUE TITLE
csv table editor option not available.

### ISSUE THREAD

**Issue by Tea7ime** [SeeSharpSoft/intellij-csv-validator#150]
This could just be me, so I'm hoping to get some usage clarity here. I am using pycharm community addition. 

If I create a new .csv file in my project, the table editor pops up just fine initially. But, if I create a few columns and rows, then click "Edit in Text Editor" the option to change back into table editor never appears. Should I expect to see that? 

Example .csv format:

test1,test2,test3
1,2,3

**Comment by SeeSharpSoft** [comment]
@Tea7ime Are you aware of the editor tabs at the bottom of the editor window? Are both available/visible to you?
![image](https://user-images.githubusercontent.com/3205800/63317047-a2850e00-c311-11e9-8384-31df2e474031.png)

**Comment by Tea7ime** [comment]
Ah, bingo! I was looking in the wrong place. Thanks for your quick response @SeeSharpSoft!
