### ISSUE TITLE
Add escape character setting

### ISSUE THREAD

**Issue by marcindabrowski** [SeeSharpSoft/intellij-csv-validator#159]
I'm aware of an answer to issue **Escaped quotes** #9, but maybe it will be a good idea to add a new setting to the plugin.
You are referring to [RFC-4180](https://tools.ietf.org/html/rfc4180) which is allowing only comma as field separator, but your plugin allows other values. There is a lot of utilities that do not escape double-quote using another double quote.
In my case also backslash **\\** char is used as an escape character.

**Comment by SeeSharpSoft** [comment]
That's a good request - I will have a look into it.

> In my case also ** char is used as an escape character

Is this a typo or do you really have two * as escape characters? I suppose in your case it would be:

`"This is a value with a *" in it"`

**Comment by marcindabrowski** [comment]
It was a typo, I'm using double quote " as escape character.
