### ISSUE TITLE
Ability to handle different separators

### ISSUE THREAD

**Issue by nokite** [SeeSharpSoft/intellij-csv-validator#162]
I know that CSV stands for comma-separated values, but there are use cases where using different separators can help (by simplifying parsing, for instance).
I suggest adding support for various separators, like: , . ;
In the best case, the separator could be freely configurable.

**Comment by SeeSharpSoft** [comment]
I'm a bit puzzled. Please read any of this:
https://github.com/SeeSharpSoft/intellij-csv-validator#features
https://github.com/SeeSharpSoft/intellij-csv-validator#separator
https://github.com/SeeSharpSoft/intellij-csv-validator#separator-1
https://github.com/SeeSharpSoft/intellij-csv-validator#file-specific-value-separator
https://github.com/SeeSharpSoft/intellij-csv-validator#faq
