### ISSUE TITLE
l just want to read csv

### ISSUE THREAD

**Issue by yycyyyc321** [SeeSharpSoft/intellij-csv-validator#163]
l just want to read csv,I don't want to edit csv file, can you set a button to enable edition?

**Comment by SeeSharpSoft** [comment]
Voilà, here you go:

![image](https://user-images.githubusercontent.com/3205800/67081987-89c19900-f198-11e9-88b2-068b4ffa0292.png)

**Comment by yycyyyc321** [comment]
thanks, get it
