### ISSUE TITLE
Multiple issues with IntelliJ

### ISSUE THREAD

**Issue by jclark-dot-org** [SeeSharpSoft/intellij-csv-validator#164]
Just added to IntelliJ:

> IntelliJ IDEA 2019.2.3 (Community Edition)
> Build #IC-192.6817.14, built on September 24, 2019
> Runtime version: 11.0.4+10-b304.69 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.5
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1979M
> Cores: 12
> Registry: 
> Non-Bundled Plugins: String Manipulation, com.illuminatedcloud2.intellij, com.potterhsu.jsonviewer, net.seesharpsoft.intellij.plugins.csv

Having several issues:
* Upon first use, could see CSV text but could not access Table view; clicking the "Table Editor" tab at the bottom produced no results.
* Found setting to open in Table Editor first; closed/re-opened file; can not access Text view.  Tried "Text" tab at bottom, as well as "Open file in Text Editor" link at top.  Screen "blinks" or "shakes" for a split second, but nothing else happens.
* When in table editor view, mouse scrolling is flaky.  Usually need to click somewhere to make it scroll.
* Cannot find an option to save (aside from File->Save All)

**Comment by SeeSharpSoft** [comment]
I am sorry to hear this - it's the first time someone mentioning issues with the editor tabs. I can't reproduce it.

> Cannot find an option to save (aside from File->Save All)

AFAIK there is no explicit save option, IntelliJ IDEs auto-save files. This behavior is not related to the plugin.

> When in table editor view, mouse scrolling is flaky. Usually need to click somewhere to make it scroll.

Noticed - I will investigate into this.
