### ISSUE TITLE
Can't Scroll Horizontally in Grid View with Mouse (WebStorm macOS)

### ISSUE THREAD

**Issue by Ognian** [SeeSharpSoft/intellij-csv-validator#169]
Only horizontal Scrolling via Mouse or Touch Pad does not work in "Table Editor" window. Scrolling with Scroll Bars Work. Scrolling wit Mouse or Touch Pad in "Text" window works too.

WebStorm 2019.3.1
Build #WS-193.5662.54, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: ide.editor.tabs.open.at.the.end=true, search.everywhere.settings=true, debugger.watches.in.variables=false
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea, com.linkedin.intellij.dust, io.probst.idea.clangformat, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, org.toml.lang, ru.adelf.idea.dotenv

**Comment by SeeSharpSoft** [comment]
Thanks for reporting - will have a look into it.

**Comment by Ognian** [comment]
Works perfekt!!
