### ISSUE TITLE
double-quote does not appear in table editor

### ISSUE THREAD

**Issue by SoftCyD** [SeeSharpSoft/intellij-csv-validator#173]
Hi,
In text view, if values are delimited by double quotes (") they do not appear in table view.
If you add double-quotes in table editor and come back to text view, there are now 3 double-quotes.

Simple-quotes are ok.

Thank you.
Cyril

**Comment by SeeSharpSoft** [comment]
@SoftCyD I don't understand the issue, can you please provide an example of CSV text that is not treated properly in the table editor. Thanks

**Comment by SoftCyD** [comment]
OK, here it is,

`
col_1,col_2
"value1",2
value1,"2"
value1,2
`

**Comment by SeeSharpSoft** [comment]
Double quotes are control characters in CSV, used to enquote values containing the delimiter or new line character. The double quotes are not part of the value they enquote. A value containing double quotes must be enquoted and the double quotes must be escaped:

col_1,col_2
"””value1"””,2
value1,””"2"””
value1,2
