### ISSUE TITLE
Feature proposal - Handle fixed length text files

### ISSUE THREAD

**Issue by Szymon2603** [SeeSharpSoft/intellij-csv-validator#174]
I would like to make proposal to add a fixed length text files handling. This kind of files are also use often, their are similar to CSV, PSV and TSV files and that format is actually hard to read and edit. It would be very cool to be able editing those files in IntelliJ.
Of course in case of those files probably there is need to create some configuration about columns and their widths as well as how they should be padded (character to pad, left or right alignment).

**Comment by SeeSharpSoft** [comment]
Thanks for the proposal. I thought a while about it and came to the conclusion, that while it is indeed a benefit in having the features of the plugin for this kind of file format, it's format and syntax has barely anything in common with CSV - only the same purpose of representing table like structured data in plain text. The lexer/parser definition is so different, that I don't consider it a derivate of CSV - it requires and deserves its own plugin.

**Comment by Szymon2603** [comment]
Ok, I get it. Thanks for response 😉. So probably I will try to write something by myself (it will be challenge, because I didn't have chance to work with intellij plugin API). I think that this issue can be closed.
