### ISSUE TITLE
Error with special characters

### ISSUE THREAD

**Issue by ptahchiev** [SeeSharpSoft/intellij-csv-validator#192]
Hello,
I have this in my CSV:
```
^((0|1|2|3)\d{1})-((0|1)\d{1})-((19|20)\d{2})
```
but the plugin detects this error and stops formatting the CSV file correctly.
![error](https://user-images.githubusercontent.com/5320045/77256283-e4927b80-6c75-11ea-9d96-00587e634825.png)

**Comment by SeeSharpSoft** [comment]
@ptahchiev Are you using the latest version of the plugin? I can't reproduce the issue locally with the latest version, and it looks similar to issue #184, which is resolved meanwhile.

**Comment by ptahchiev** [comment]
Hey, thank you for your fast response - yes it works fine now with the latest version :). Closing this issue.
