### ISSUE TITLE
Support for Latest PHPStorm

### ISSUE THREAD

**Issue by fsthomas** [SeeSharpSoft/intellij-csv-validator#193]
I noted that the documentation says: 

> This version is not compatible - and will therefore not work properly - with never versions (>= 2019.3.*) of the IntelliJ IDE.

Is there any hopes of adding support for PHPStorm version 2019.3+? 

For example, I'm currently running 2019.3.4 and cannot view CSVs as tabular data.

**Comment by SeeSharpSoft** [comment]
You are citing out of context:

> Due to a bug in all editions of IntelliJ 2019.2.*, the plugin now comes in two versions. Both versions are identical except a configuration workaround, which is only part of the version ending with -192. This version is not compatible - and will therefore not work properly - with never versions (>= 2019.3.*) of the IntelliJ IDE.

The [CSV plugin version](https://plugins.jetbrains.com/plugin/10037-csv-plugin/versions) without the *-192* works for all other version besides 2019.2.* - also for PHPStorm. What is the actual issue?
