### ISSUE TITLE
Recommended feature: Table-like Editor

### ISSUE THREAD

**Issue by claudiu-marginean** [SeeSharpSoft/intellij-csv-validator#2]
I like the fact that it validates and highlight into in CSV files. 
But I was looking to the table like editor that is present in PhpStorm.

Maybe you can enable it by default and use it in this extension ;)

https://www.jetbrains.com/help/phpstorm/editing-csv-and-similar-files-in-table-format.html

**Comment by SeeSharpSoft** [comment]
Yes, I am aware of this feature for the non-community edition of JetBrains IDEs (also available in IntelliJ IDEA Ultimate - https://www.jetbrains.com/help/idea/editing-csv-and-similar-files-in-table-format.html).

Enabling the table like editor through this plugin is for obvious reasons not possible.

Said this, contributions providing a similar functionality without violating the IP of JetBrains are always welcome! ;)

**Comment by JulianRaya** [comment]
If you don't mind me asking, what are the "obvious reasons" that make table like editor not possible?

**Comment by SeeSharpSoft** [comment]
I pointed it out just in the next sentence...

But let me be straight: The database plugin, that is providing this feature to a bunch of JetBrains IDEs, is not part of the IntelliJ Community edition, it is the core component of [JetBrains DataGrip](https://www.jetbrains.com/datagrip/). It is neither open source nor does it come with a "do-whatever-you-like" licensing model - I cannot afford the rightful lawsuit when distributing this ~40 MB library as part of my ~100 KB plugin... ;)

**Comment by JulianRaya** [comment]
Woah, that's lame of them.
Is this the same when developing plugins for the full version? Because there still seems to be a lack of useful functionality in most plugins, and the point you make seems to be a likely reason for that.

**Comment by SeeSharpSoft** [comment]
No, there is nothing lame about it. You can develop and contribute funtionality that you would like to see, there are no restrictions. Just don't "contribute" other peoples work, that would be lame!

**Comment by SeeSharpSoft** [comment]
@opticyclic For me the most important requirement is that it fits well in the IntelliJ framework and the already existing editor/UI API. I haven’t digged into this part yet so I can’t name which UI components are suppossed to be used (or if there are any at all).

When I think about this feature it should be an alternative editor view (like the second tab of DataGrip) but without providing additional features that would be only available in this view.
For me personally the benefit of CSV is having the data in a pure text format. The table representation or even editor is quite nice in certain situations - but having a good text editor experience for CSV in general is IMO much more benefical and should stay in the focus of this plugin.

**Comment by flomock** [comment]
Hey thank you for the cool plugin, if've recently seen a feature in [visual studio code](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv) were every 10 columns get different colors. In my opinion this should not be to hard to implement and really helps for a quick overview of the data. 
thank you for your work

**Comment by SeeSharpSoft** [comment]
I am happy to announce that [CSV Plugin 2.*](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/2.0.0) features a table-like editor!
