### ISSUE TITLE
Memory issues and freezes after updating

### ISSUE THREAD

**Issue by Olegandr** [SeeSharpSoft/intellij-csv-validator#204]
PyCharm 2020.1.1
after updating to the current version of plugin excessive memory usage,
cannot open CSV file, PyCharm fails to open projects, uses 1.5 GB RAM
Unloading CSV Plugin makes it use 400 MB Ram.
[pycharm-logs-20200508-154149.zip](https://github.com/SeeSharpSoft/intellij-csv-validator/files/4602056/pycharm-logs-20200508-154149.zip)

**Comment by SeeSharpSoft** [comment]
@Olegandr Thanks for reporting - I am investigating!

**Comment by SeeSharpSoft** [comment]
The reason for this exception is a faulty lexing of CSV files containing a COLON (:), which was newly introduced as a predefined separator in 2.11.0.

I prepared a hotfix (release 2.11.1). It usually takes 1-3 workdays until the new release is validated by Jetbrains and available via the plugin repository. The new version can also be manually installed from [here](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/2.11.1).

**Comment by Olegandr** [comment]
Thank you for prompt response and fix!

**Comment by damithc** [comment]
Stumbled upon the same problem (see [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008179780-IDEA-2020-1-anyone-noticing-increased-memory-usage-?page=1#community_comment_360001650100))
Good to hear a fix is in the works. Thanks @SeeSharpSoft

**Comment by kdschlosser** [comment]
I believe this may be the same issue I am running into. When opening a CSV file PyCharm simply hangs and consumes memory until it hits the maximum heap allocation allowed. No errors in the log. In fact there is nothing written to the log once this happens.

**Comment by znerd** [comment]
Sounds like the same problem I'm running into. When opening a CSV file, my IntelliJ IDEA (Ultimate) 2020.1.1 just hangs and starts eating more and more memory until it reports that the allotted 4 GB is not enough…

![Screen Shot 2020-05-11 at 13 23 44](https://user-images.githubusercontent.com/117866/81568247-cc99c700-939d-11ea-84e0-8a664ce191f5.png)

**Comment by fcrick** [comment]
Also had to disable plugin after most recent update. PHP Storm would run out of memory almost instantly and I was only able to disable the plugin after a few tries.

**Comment by kdschlosser** [comment]
if you download the jar file that is attached a few posts up you will need to rename it so the version ends with 0 and overwrite the one in the plugins folder. then everything will work properly.

**Comment by CrazyCoder** [comment]
A dozen of duplicate reports in YouTrack, see https://youtrack.jetbrains.com/issue/IDEA-240713 and the linked issues.

**Comment by SeeSharpSoft** [comment]
@CrazyCoder I am genuinely sorry for causing this extra workload on your side. And Thank you for stating/sharing the solution incl. corresponding links!

**Comment by dereuromark** [comment]
I ran into the same 4GB memory issues and hundreds of freezes/restarts until I found this one here.

**Comment by brianbautista** [comment]
The latest update (v2.11.1) fixed the memory leak for me 👍 
Using PyCharm CE 2020.1.1
