### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kdschlosser** [SeeSharpSoft/intellij-csv-validator#206]
when I double click on the column divider in the table view the expected result is to automatically set the column width to the widest cell in that column. instead it makes it the size of the header field. If I have the headers turned off then it sizes it to a single character. I am not sure if this is by design but the typical outcome is for the column to automatically set it's self to the width of the cell that has the longest data.

also being able to turn off the line wrapping would be a nice feature. 

I do remember someone stating that when editing using the table view double quotes get added. I believe that with CSV double quotes should only get added if the data has a comma or a new line character.

right justification of integers and floats. wouldn't be a bad idea wither possibly some alternative color coding for those items could be used. have it follow the editors settings for these items.

checkbox to enable/disable data being shown in a column.

search when in table view

merge 2 CSV files having the option of pointing data from one file's column to another files already existing column or insert/appending the column into the destination file.

split screen view between text editor and table view.

adjustment of row height via gripper between rows.
allow gripper between cells that are not header cells to adjust column width and row height

setting an index column 
sorting file

I am sure I will think of a few more things It is a good plugin how it is. It would be a great plugin if the above features were added.

**Comment by SeeSharpSoft** [comment]
@kdschlosser This are some quite useful suggestions. Could you split them up into multiple issue with just one suggestion each for being able to track and process them individually. Thanks!

**Comment by kdschlosser** [comment]
I would be more then happy to do that for you.

**Comment by SeeSharpSoft** [comment]
@kdschlosser Thanks for splitting this up, hence closing this one.
