### ISSUE TITLE
Resize column width by dragging

### ISSUE THREAD

**Issue by RockyMM** [SeeSharpSoft/intellij-csv-validator#208]
I would love to be able to adjust column widths by dragging line which is column separator.

**Comment by SeeSharpSoft** [comment]
@RockyMM Do you mean in the text-editor?

**Comment by RockyMM** [comment]
I meant in Table Editor.

I see now, I was hovering over cells and trying to resize columns, but actually this is enabled when dragging headers :) Silly me 😅 

I will close it.
