### ISSUE TITLE
Could you improve it with a feature to rearrange the columns?

### ISSUE THREAD

**Issue by chengdi123000** [SeeSharpSoft/intellij-csv-validator#22]
I found it is impossible to exchange columns in CSV plugin's data view and save it to csv file. 

I tried to copy content to clipboard and paste it back to csv file. It is still not working properly.

**Comment by SeeSharpSoft** [comment]
@chengdi123000 I am not quite sure what you are refering to by “CSV plugin’s data view”. This plugin does not come with an additional view but provides common editor features.

One of such a feature are Intentions, which can be accessed with the keyboard shortcut ALT+ENTER when your editor window is focused. The type of available intentions are based on the file type and the position of your cursor within the document. The CSV plugin provides the “Shift Column Left”/“Shift Column Right” intention for CSV/TSV file types. More information can be found in the `README.md`. In general there is no need for any clipboard action.

**Comment by chengdi123000** [comment]
I am sorry for the confusion. `CSV plugin's data view` means the `data` tab, comparing with `text` tab.

Thank you for your reply. I can do column shift now.

**Comment by SeeSharpSoft** [comment]
That's great to hear!

Just for a complete and clear understanding: The `data` tab is NOT a functionality of this plugin, it comes from the "Edit as Table..." functionality provided by the Jetbrains DataGrip library (see also #2).
