### ISSUE TITLE
Default Value Separator get frequently reset to comma, changes only applied after restart

### ISSUE THREAD

**Issue by klamann** [SeeSharpSoft/intellij-csv-validator#222]
I'm working with CSV files that use the Semicolon as separator. When I change the setting "Default Value Separator (CSV only)" to "Semicolon (;)", the change is not applied immediately, which means the Table Editor does not display the CSV correctly until I close the CSV file, restart the IDE, change the setting and then open the file again (just re-opening the file is not enough).

The second problem is that the setting "Default Value Separator (CSV only)" gets frequently reset to "Comma (,)". I'm not sure when this happens, but it seems to happen most times when I (re)start the IDE. This is especially annoying, because now I have to change the setting once more, close all my CSV files, restart the IDE and open the files again.

Can you please investigate, why this setting gets reset, and maybe make it so that the change is applied immediately, or at least only requires to re-open the file instead of restarting the IDE?

CSV Plugin 2.11.1, PyCharm Community 2020.1.1

edit: changed the description of the workflow to open the CSV; you have to change the setting *after* you restart the IDE. It won't work if you do it before you restart, that will just reset the setting to comma.

**Comment by SeeSharpSoft** [comment]
@klamann Thanks for reporting - I am having a look.

**Comment by SeeSharpSoft** [comment]
Resolved in latest version
