### ISSUE TITLE
[Suggestion] Prompt to change separator character if file doesn't parse

### ISSUE THREAD

**Issue by jrynd** [SeeSharpSoft/intellij-csv-validator#223]
At my company, policy is that files are given .csv extension but use pipes to delimit. (I know, they should switch to proper CSV format or use .psv extension but I can't change that policy.)

Would like to, when opening a CSV file, if no commas are detected but many of the other possible separators are, to prompt to change the file's separator character rather than displaying a cryptic error message.

**Comment by SeeSharpSoft** [comment]
Sounds like a neat feature - adding it to the list.

Meanwhile you can define the default separator for your CSV files:
https://github.com/SeeSharpSoft/intellij-csv-validator#default-value-separator-csv-only

**Comment by SeeSharpSoft** [comment]
The newly introduced [Auto Detect](https://github.com/SeeSharpSoft/intellij-csv-validator#auto-detect) feature in 2.14.4 covers this suggestion.
