### ISSUE TITLE
Register .tsv as supported file extension

### ISSUE THREAD

**Issue by sabi0** [SeeSharpSoft/intellij-csv-validator#24]
According to this comment https://youtrack.jetbrains.com/issue/IDEA-190335#focus=streamItem-27-2825719-0-0 `.tsv` file extension has not been registered in the plugin description XML.
Adding it there will make IDEA suggest the plugin for *.tsv files

**Comment by SeeSharpSoft** [comment]
@sabi0 Thanks - I hope I'll get an answer soon from the referenced thread.

**Comment by SeeSharpSoft** [comment]
Resolved by Jetbrains support ([Issue tracker](https://youtrack.jetbrains.com/issue/IDEA-190335), [community post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000510864-How-to-register-a-supported-format-in-plugin-description-XML))
