### ISSUE TITLE
Editor format abnormal

### ISSUE THREAD

**Issue by SiMaLaoShi** [SeeSharpSoft/intellij-csv-validator#242]
![image](https://user-images.githubusercontent.com/28924681/90117020-e83faf80-dd88-11ea-84e6-e48ba59d1748.png)

**Comment by SeeSharpSoft** [comment]
It's not a bug, [its a feature...](https://github.com/SeeSharpSoft/intellij-csv-validator#line-comment-indicator) 😉

As written in the docu, clear the 'Line Comment Indicator' input to disable comment support.
