### ISSUE TITLE
files are not recognized as .csv

### ISSUE THREAD

**Issue by kevindtimm** [SeeSharpSoft/intellij-csv-validator#251]
I have a large collection of .csv files but only about 20% of them are recognized by the plug-in
I'm running 2.14.3 on goland 2020.2.3
Is there a way to find out why my files aren't recognized?

**Comment by SeeSharpSoft** [comment]
@kevindtimm Sorry for the late response, I was quite busy the last weeks. Is the issue still relevant?

My initial guess would be that either the indexing was still ongoing, or that some file-extensions (this plugin registers .csv, .tsv, .tab and .psv) are not associated with this plugin (see Settings -> Editor -> File Types).

**Comment by kevindtimm** [comment]
It seems to work now, I haven't seen more issues.
