### ISSUE TITLE
".editorconfig" - export error

### ISSUE THREAD

**Issue by voku** [SeeSharpSoft/intellij-csv-validator#252]
If I try to save the code style via PhpStorm, there is an error in the export (.editorconfig) output.

```
[]
max_line_length = 2147483647
ij_csv_wrap_long_lines = false
```

---

PhpStorm 2020.3 EAP
Build #PS-203.5784.36, built on November 12, 2020
PhpStorm EAP User
Expiration date: December 12, 2020
Runtime version: 11.0.9+11-b1145.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-123-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, String Manipulation, com.alayouni.ansiHighlight, com.andrey4623.rainbowcsv, com.intellij.ideolog, dev.arunvelsriram.desccron, net.seesharpsoft.intellij.plugins.csv, uk.co.ben-gibson.remote.repository.mapper, name.kropp.intellij.makefile, NEON support, com.kalessil.phpStorm.phpInspectionsUltimate, me.artspb.idea.eval.plugin, net.king2500.plugins.PhpAdvancedAutoComplete, lv.midiana.misc.phpstorm-plugins.deep-keys, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv
Current Desktop: ubuntu:GNOME

**Comment by SeeSharpSoft** [comment]
Might be a regression bug of the editorconfig export - the export format looks fine with an earlier version I tested it with (see also https://youtrack.jetbrains.com/issue/WI-57035). I will wait for the response of Jetbrains.

**Comment by SeeSharpSoft** [comment]
https://youtrack.jetbrains.com/issue/IDEA-256364

**Comment by SeeSharpSoft** [comment]
Resolved by Jetbrains
