### ISSUE TITLE
Change delimiter recognized

### ISSUE THREAD

**Issue by 5t4cktr4c3** [SeeSharpSoft/intellij-csv-validator#258]
Hi,
I have two CSV files. Both are using the delimiter `,`. However, in one files the `,` is recognized as delimiter and will therefore create a readable table. In the second file the delimiter is not recognized and the data are displayed as a single column.
How do I change the delimiter recognized?

**Comment by SeeSharpSoft** [comment]
The separator can be defined for each file via the [corresponding action in its editor context menu](https://github.com/SeeSharpSoft/intellij-csv-validator#file-specific-value-separator--escape-character).

**Comment by 5t4cktr4c3** [comment]
Thanks, in the first place I thought this action is available when right-clicking the specific file. However, it's right clicking inside the editor window (maybe this will help someone).
I have another question: When selecting `Edit as table` from the editor context menu (plugin `Database Tools and SQL` it will create a tab inside the editor window. How do I close these tabs?

**Comment by SeeSharpSoft** [comment]
Sorry for the late response, but I can't provide support for the `Edit as table` handling.
