### ISSUE TITLE
Rainbow Values no longer works

### ISSUE THREAD

**Issue by christopherpicard** [SeeSharpSoft/intellij-csv-validator#265]
I just updated to the latest version of the plugin and the rainbow value capability appears to have broken. I verified it is still selected in settings but I no longer see the rainbow values in the editor.

**Comment by SeeSharpSoft** [comment]
ups, you are absolutely right... Thanks for reporting!

**Comment by christopherpicard** [comment]
No problem, I use that feature all the time so easy to spot. Just downloaded the fix and it works for me. Appreciate the quick turn around!
