### ISSUE TITLE
Ability to split on ASCII separator character \x1e

### ISSUE THREAD

**Issue by barrycoleman** [SeeSharpSoft/intellij-csv-validator#267]
The ASCII character RS (Dec: 30, Hex, 1E) is the record separator character.
We get a lot of files with this as the separator and it solves a lot of issues with commas and quotes.

Would be nice if the CSV plug-in could handle files with that as the field seprator.

It does work using the custom separator but it's really tricky to get the character in there.
Would be easier if it was a pre-defined.

**Comment by SeeSharpSoft** [comment]
Available since 2.16.0
