### ISSUE TITLE
Default Value Separator does not work

### ISSUE THREAD

**Issue by mathiasrabe** [SeeSharpSoft/intellij-csv-validator#290]
Hi, I'm using PyCharm 2021.1.1 and CSV Plugin 2.16.3.

I've changed the Default Value Separator to "Semicolon (;)" and disabled the "auto detect initially" option. My CSV-file looks like this:

```
0,000000;17213
0,000080;17539
an so on ...
```

The Table Editor still separates the values at the , sign and not at the ;

**Comment by SeeSharpSoft** [comment]
If the file was previously opened, the assumed separator is already stored in the plugins file-attribute store. Use the editors context menu action [CSV Value Separator](https://github.com/SeeSharpSoft/intellij-csv-validator#file-specific-value-separator--escape-character) to change it in those cases. The new settings can only be applied to newly-opened or -created files.
