### ISSUE TITLE
TSV formatting

### ISSUE THREAD

**Issue by vovakyrychenko** [SeeSharpSoft/intellij-csv-validator#293]
![image (1)](https://user-images.githubusercontent.com/120864/121217054-2531e100-c88a-11eb-9488-a9fe6090dc17.png)

TSV separated by tabs during reformat gets additional spaces that have semantic meaning during the parsing, hence breaks the content of the file.

The plugin should not add spaces into TSV files.

**Comment by SeeSharpSoft** [comment]
Please disable "Tabularize" in the [codestyle settings](https://github.com/SeeSharpSoft/intellij-csv-validator#tabularize-enabled-default).
