### ISSUE TITLE
Show diff opens an empty window

### ISSUE THREAD

**Issue by rala72** [SeeSharpSoft/intellij-csv-validator#306]
If I open a diff window the first time in a project and it is a CSV file the CSV editor opens an empty window.
Afterwards I am not able to open any diff anymore - including other file types - the CSV diff always shows an empty file.
The only solution I found yet is restarting the project.

If I open a diff on another file first the basic diff window opens also on CSV files.

_Honestly not sure if this an issue of that plugin but I think so (sorry if not)._

**Comment by SeeSharpSoft** [comment]
Thanks for reporting - unfortunately I either don't understand the issue correctly, or I cannot reproduce it.

What do you mean by "open a diff window"? Is it the option `EditorContextMenu -> Git -> Show Diff`, or `FileContextMenu -> Compare With...`? Both options seem to work fine.

You could just disable the plugin (and restart IDE) to check whether the issue persists. If this fixes the issue, then please give a more detailed description of the steps, or add a screen-capture to this issue, so I can hopefully reproduce it.

**Comment by rala72** [comment]
Sorry for being unclear; yes, after unloading the plugin the issue is gone.

I'm meaning the option `Git-Tool window -> Log -> Commit Content -> ContextMenu -> Show Diff`.
As far as I tried all other options work, but the way listed above breaks all the same kind.
_(I can't provide a screenshot, because it is my business project and I was not able to reproduce it on a private one yet)._

**Comment by SeeSharpSoft** [comment]
Thanks for the clarification.

Unfortunately I am not able to reproduce it locally, even when following the path you noted down directly after starting the IDE.

Can you provide IDE type (IDEA, WebStorm, PyCharm, etc.), version, Java version and your operating system (Win/Mac/Linux/...) please. Thanks!

**Comment by rala72** [comment]
Windows 10
Java AdoptOpenJDK (build 11.0.10+9, 64bit)
IDEA Ultimate; 2021.2.2 (212.5284.40)

Below a screenshot of the dialog that pops up _(the git log is partly seen in the background)_:
![screenshot](https://user-images.githubusercontent.com/6838669/135973805-791d386d-3a1a-45da-9d1f-5d1d1623328e.png)
It never also stops indexing (IJ already stopped indexing).
