### ISSUE TITLE
Highlight Tab Characters

### ISSUE THREAD

**Issue by egoisticalgoat** [SeeSharpSoft/intellij-csv-validator#31]
It would be nice to have tab characters in tab separated files coloured according to the colours defined in `Color Scheme->CSV->Separators`.

**Comment by SeeSharpSoft** [comment]
@egoisticalgoat I just gave it a try and it is actually working. Please note that the default settings do not provide a noticable background color or effect for tabs - but you can adjust it to your liking:

![image](https://user-images.githubusercontent.com/3205800/41556275-8e815eae-733a-11e8-9a68-9de007c6d200.png)

**Comment by egoisticalgoat** [comment]
Oh, seems like i didn't look close enough :sweat_smile: 
Apparently, setting the foreground color doesn't affect the arrow that represents the tab character. My bad.
