### ISSUE TITLE
Ability to auto-reload changed files.

### ISSUE THREAD

**Issue by pjewell-biociphers** [SeeSharpSoft/intellij-csv-validator#316]
Hello, first off I'd like to thank all involved for the handy tool ; it's far superior to viewing the unformatted text and the only viable alternative is using libreoffice calc. 

Anyway, by usual use case is not editing TSV but rather viewing output from programs I'm developing, so make sure results are correct or debug certain situations. One problem I've had with this plugin is that, unlike other files in Pycharm, when there are external changes to the file (for example, by re-running a program), there is no way to reload. Ideally, I would like the reloading to be automatic, like other files in pycharm, but I've noticed even the manual "File > Reload all from disk" option does not update the output, the only way is to close the TSV tab and double click it in the treeview again. 

Any possibility of adding an option for auto reload?

**Comment by SeeSharpSoft** [comment]
Thanks for the suggestion. I will investigate why CSV files are not reloaded in the editor, or how to enable it.
