### ISSUE TITLE
FIX: java.lang.NullPointerException #320 FIX: Exception when Show info balloon is not selected #318

### ISSUE THREAD

**Issue by Veng0923** [SeeSharpSoft/intellij-csv-validator#325]
![image](https://user-images.githubusercontent.com/34118386/150244145-b65b82d7-d1b6-4317-a6e8-209d99868839.png)

**Comment by SaxMan96** [comment]
Did you find any solution for that issue?

**Comment by SaxMan96** [comment]
I haven't seen it recently.
