### ISSUE TITLE
The file parse stops if there is a strange double-quote character

### ISSUE THREAD

**Issue by gbonline** [SeeSharpSoft/intellij-csv-validator#329]
Hi,
the file parsing stop with  the file attached because there is a strange double quote char to indicate a inch size.

my system is win10 64bit - ita language 
pycharm PyCharm 2021.3.3 (Community Edition)
Build #PC-213.7172.26, built on March 16, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation

csv plugin : latest
[sample_seller.csv](https://github.com/SeeSharpSoft/intellij-csv-validator/files/8305364/sample_seller.csv)

**Comment by SeeSharpSoft** [comment]
The provided file just doesn't follow the CSV format properly regarding the usage of quotes, therefore the parser stops and marks it as an error. See also #9 or #60 for further reference.
