### ISSUE TITLE
Error while parsing content!

### ISSUE THREAD

**Issue by ericmarquesf** [SeeSharpSoft/intellij-csv-validator#330]
Hello, Martin Soomer! 

First of all, thank you for that wonderful plugin, it has been helped a lot! 

As you can see in the attached print, I can't use the CSV plugin correctly. There is no error in my script. (When I execute it, no error is shown). Two days ago everything was fine, but started to appear this error. 

I really enjoy using your plugin, makes my job easier.

Can you help me? 

Sincerely, Eric Marques

![Screenshot_1](https://user-images.githubusercontent.com/106750433/171633984-b2217812-9292-4f19-894b-febad0013051.png)
![Screenshot_2](https://user-images.githubusercontent.com/106750433/171633989-1ceef541-6268-4478-b018-463196b0b517.png)
s

**Comment by SeeSharpSoft** [comment]
@ericmarquesf Sorry for the late response. The Table Editor is not working cause of the error shown in the Text Editor. Unfortunately I can't really point the issue down exactly, but it seems that the [CSV separator or escape character settings](https://github.com/SeeSharpSoft/intellij-csv-validator#file-specific-value-separator--escape-character) are a bit off for this file.
