### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by a-Rahmati** [SeeSharpSoft/intellij-csv-validator#334]
Hello,

When I open a CSV file it takes a while to open it and uses about the whole of my CPU. I don't know if it's a problem or OK.

It's a short clip that shows delay and CPU:

https://user-images.githubusercontent.com/52320192/181823873-33d8cc75-c414-4ded-b957-8a5d197c62ca.mp4

My PC Information:

![image](https://user-images.githubusercontent.com/52320192/181824498-83c921d7-31a1-4280-9d32-4d7ad102fd4c.png)

Thanks

**Comment by SeeSharpSoft** [comment]
@a-Rahmati Thanks a lot for pointing this out!

I just invested quite some time into improving the performance and memory footprint - and it really paid off (planned for upcoming release 2.20.1).

However, there is more to come but it requires major changes, so I will target those in a new major release. I will keep this issue open!

**Comment by halilim** [comment]
Thank you for the great plugin. I can't see a specific error, so I hope this is the correct place to add this. A 2.3 MB file takes more than ~10 seconds on my system (Macbook pro/24-core M1 Max/32 GB, plugin version: 2.21.0, IDE: RubyMine 2022.2.3). For reference, it loads in 1-2 seconds on some other plugins/editors, so I don't think it's the file.

**Comment by SeeSharpSoft** [comment]
@halilim Thanks for sharing.

Can you provide some details about your settings:
- Is it for opening the text editor or the table editor?
- Do you use a custom value separator, or a different line comment indicator (other than '#')?
- Is [default separator detection](https://github.com/SeeSharpSoft/intellij-csv-validator#auto-detect) enabled (default)? This might take some time when opening a large document for the first time. So did you notice this poor performance when opening it again?
- Do I get you right that when you just disable the plugin, the editor opens in 1-2 seconds, but with the plugin enabled it takes like 10 seconds to show the content in the editor? Or do you talk about the indicator that it is analyzing?

I tested it with a similar large file on my Windows system (i7/8-core, 16 GB) and it takes like 0-3 seconds to open in text editor. The table editor still lacks performance and I am currently doing a big overhaul, but I can't reproduce the performance you are describing with the latest version in the text editor. Before release 2.21.0 the numbers wouldn't surprise me, but now they actually do...

**Comment by halilim** [comment]
> * Is it for opening the text editor or the table editor?

It seems it's for opening the table editor.

> * Do you use a custom value separator, or a different line comment indicator (other than '#')?

I use the default separator (`,`) and the default comment indicator (`#`). The file has no comments. It has a few links within some text columns in the form `https://example.com/foo#bar`. I removed them and it seems it doesn't make much difference.

> * Is [default separator detection](https://github.com/SeeSharpSoft/intellij-csv-validator#auto-detect) enabled (default)? This might take some time when opening a large document for the first time. So did you notice this poor performance when opening it again?

It was enabled. I disabled it but it's still the same.

> * Do I get you right that when you just disable the plugin, the editor opens in 1-2 seconds, but with the plugin enabled it takes like 10 seconds to show the content in the editor? Or do you talk about the indicator that it is analyzing?

When the plugin is disabled, or if I open it in the text editor, it opens pretty much immediately. With the plugin on, it takes 15-20 seconds to load in table editor mode (or to switch to it, if it was open in the text mode). Sometimes it seems it's loaded, but then it takes that long to actually become responsive.

FWIW:

- Many/most rows have text columns spanning multiple lines
- There are some `NBSP` characters

I will try to set aside some time and create a non-proprietary dummy version of the file. If I can reproduce it with that, I can attach a CPU usage profile snapshot.

**Comment by SeeSharpSoft** [comment]
Thanks a lot for taking the time and providing all the details!

As mentioned briefly, the table editor has quite numerous performance issues that I'm currently working on. All performance related changes until now where targeting the lexer/parser and the text editor. So yes, it actually (and unfortunately) takes that much time for the table editor to open, but I believe it will come down to 1-3 seconds once I'm done with the full refactoring.

**Comment by halilim** [comment]
Thank you for the great work! Indeed, the table mode now opens almost instantly.
