### ISSUE TITLE
Chinese format error

### ISSUE THREAD

**Issue by frogeater1** [SeeSharpSoft/intellij-csv-validator#343]
![image](https://user-images.githubusercontent.com/100656395/197499557-55b9f36a-aa46-431d-83e9-c4f3f9ca54ce.png)

**Comment by frogeater1** [comment]
![image](https://user-images.githubusercontent.com/100656395/197499450-e62b193d-b9b7-41b4-80c6-5d134578fe9b.png)

**Comment by SeeSharpSoft** [comment]
see #48 - support must be enabled in CSV format settings (it slows down the formatting on large files)
