### ISSUE TITLE
Add button to execute/import csv

### ISSUE THREAD

**Issue by ptahchiev** [SeeSharpSoft/intellij-csv-validator#35]
Most CSV files are used to import data into some system. 
It would be super nice if there was a way to directly execute CSV files while writing it (see screenshot).

![image 1](https://user-images.githubusercontent.com/5320045/41651052-40ebd1de-7488-11e8-8e80-04d743be3ed6.png)

Also if this is implemented we might need a textarea in the settings where the user can write some groovy code what should happen when the button is clicked (in our case it makes `POST` request to `https://localhost:8112/storefront/platform/csv/import`)

**Comment by SeeSharpSoft** [comment]
@ptahchiev I am with you that CSV is mostly used for data export/import and we are using CSV in my team exactly for that.

The feature sounds "nice-to-have" but it is not CSV specific, it does not support editing or working with CSV itself. This feature could be useful for any kind of data/file-format.

If I get you right, you are basically asking for a generic action button to execute a groovy script. It seems that the plugin [Run Configuration as Action](https://plugins.jetbrains.com/plugin/9448-run-configuration-as-action) is what you are looking for. Please note: This is not a recommendation as I have not used or tested the plugin! I just did a quick search, maybe there are other and even better fitting ones.

**Comment by ptahchiev** [comment]
Thank you for your feedback @SeeSharpSoft I was able to implement a custom plugin that does exactly what I need :))

**Comment by SeeSharpSoft** [comment]
@ptahchiev Great to hear! I consider this issue resolved then...
