### ISSUE TITLE
Add option for wrapping lines

### ISSUE THREAD

**Issue by ptahchiev** [SeeSharpSoft/intellij-csv-validator#36]
Hello,

following this question here:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000055319-Line-wrapping-csv-file

I have a problem that my csv files are being line-wrapped and now it becomes extremely hard to edit them. So for now I edit them in notepad :(
Can you please add boolean setting to enable/disable the line-wrapping for csv files (seems like currently the settings are taken from the right margin field). Thank you

**Comment by SeeSharpSoft** [comment]
@ptahchiev Which IDE version are you using? At which point in time does the wrapping happen? Did you enable 'Wrap on typing' (see screenshot)?
![image](https://user-images.githubusercontent.com/3205800/41822292-cfd6a096-77ed-11e8-87ae-59ae59350d60.png)

If it is disabled, the editor shouldn't wrap the lines - also not on code formatting. That's at least what I got from testing and digging into the default values.

I will enable this settings to be customizable for CSV files - just to be independent of the default setting.

**Comment by ptahchiev** [comment]
Hi @SeeSharpSoft 
 - I'm using IntellijIDEA 2017.2 Community edition.
 - `Wrap on typing` is off and my `hard wrap at` is 1000 (I can't set it higher).
 - Here's my file if you want to test: https://gist.github.com/ptahchiev/cdce2596bd7bcd6a074e44464f31d482
BTW I was editing the file and formatted the file and it was all fine. Then I restarted the IDEA and now it is line-wrapped and i can't make it unwrap the lines no matter what I do :(

**Comment by SeeSharpSoft** [comment]
@ptahchiev Have a look at the referenced PR. Besides providing these settings, it is possible to set the right margin to MAX_INTEGER programmatically, which seems to be also taken into account.

**Comment by SeeSharpSoft** [comment]
@ptahchiev This is the build of the FB, please let me know if it works for you: [CSV Plugin-1.7.1.zip](https://github.com/SeeSharpSoft/intellij-csv-validator/files/2131199/CSV.Plugin-1.7.1.zip)

**Comment by ptahchiev** [comment]
Ho @SeeSharpSoft unfortunately it doesn't :( I see the default settings are Integer.MAX_VALUE, but look at the screenshot 
![wrapping](https://user-images.githubusercontent.com/5320045/41823642-100fa2fc-780c-11e8-8560-ec8d2c5f05f6.png)

**Comment by SeeSharpSoft** [comment]
@ptahchiev Oh, I see - it seems to be about the softwrapping. Did you try right click on the grey area with the line numbers and disable softwrapping for the file?

For a CSV specific solution of the softwrapping I have bad news: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206246969-how-to-enable-disable-line-wrapping-based-on-file-type

You can follow the link to the related open issue and vote for it. However, the issue was opened a long time ago but it is still unresolved - the latest votes are of 2018.

**Comment by ptahchiev** [comment]
@SeeSharpSoft Wooooooooooow thank you so much - it worked!!! :)) I'll vote for the other issue :)
