### ISSUE TITLE
PhpStorm Issue

### ISSUE THREAD

**Issue by plumastudio** [SeeSharpSoft/intellij-csv-validator#4]
Hi, I have an issue in PHP Storm:
**_java.lang.NoClassDefFoundError: com/intellij/psi/PsiElementFactory$SERVICE_**

Thanks in advance for every kind of support.
Have a nice day!

**Comment by SeeSharpSoft** [comment]
[com.intellij.psi.PsiElementFactory is not included in PhpStorm](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000678690-com-intellij-psi-PsiElementFactory-not-available-in-PhpStorm-SDK-EAP-) - as it is only used once within the plugin, I will remove the dependency and re-implement the used factory function.
