### ISSUE TITLE
Not work at all on Mac

### ISSUE THREAD

**Issue by mirage93i** [SeeSharpSoft/intellij-csv-validator#404]
v. 3.0.2-223 does not work. CSV files shown as simple text files. PyCharm 2022.3.1 (Community Edition) last stable release.

**Comment by SeeSharpSoft** [comment]
Does [this](https://github.com/SeeSharpSoft/intellij-csv-validator#csv-editor-doesnt-seem-to-work) help?

**Comment by mirage93i** [comment]
it works. Thank you so much

On 25 Jan 2023, at 19:41, GeeK ***@***.***> wrote:



Does this<https://github.com/SeeSharpSoft/intellij-csv-validator#csv-editor-doesnt-seem-to-work> help?
