### ISSUE TITLE
Table Editor no longer available

### ISSUE THREAD

**Issue by Katlego-K** [SeeSharpSoft/intellij-csv-validator#414]
Hi after updated CSV Editor to 3.0.3-233 the table editor tab is no longer available, 
is a painful when dealing with a long list of data. Please assist
![2023-02-16_15h24_30](https://user-images.githubusercontent.com/34712841/219376756-08e498d4-b1fb-46b6-9f08-2956cd43106f.png)

**Comment by DespuesLeeWallace** [comment]
Same here, it does not work after an update. I reinstalled the plugin but nothing...

**Comment by Katlego-K** [comment]
How do we resolve this issue?

**Comment by SeeSharpSoft** [comment]
Did you check the the (file type association)[https://github.com/SeeSharpSoft/intellij-csv-validator#features-of-the-csv-editor-are-not-available], or the (editor usage)[https://github.com/SeeSharpSoft/intellij-csv-validator#editor-usage]? If none of this works, please provide further details like used IDE & version.

**Comment by DespuesLeeWallace** [comment]
Thanks it was the file type association.
