### ISSUE TITLE
Unexpected/unwanted hightlighting

### ISSUE THREAD

**Issue by magner58** [SeeSharpSoft/intellij-csv-validator#43]
Hey, I think since recent update (1.7.0), when the cursor is at any row except the last on, I get all rows of the csv file highlighted with magenta-like color, making it difficult to see other highlights. See attached screenshots:

Cursor at line before the last one - everything highlighted, annoying:
![csv_plugin_1](https://user-images.githubusercontent.com/13498110/42091906-629b6b2a-7ba7-11e8-9495-64a6f937e289.jpg)
Cursor at the last line - no highlighting, everything fine:
![csv_plugin_2](https://user-images.githubusercontent.com/13498110/42091908-62bb9f94-7ba7-11e8-83fb-f6668183fd4c.jpg)

Moreover, all rows are also highlighted same way in git diff panel, which makes it difficult to spot the changes.

**Comment by SeeSharpSoft** [comment]
@magner58 Thanks for your feedback!

First lets gets the reason for the highlighting straight: It marks the column where the cursor is currently placed in. In your example you are using semicolon as separator - if you do so, you should change the separator in the CSV format settings to semicolon as well (*File > Settings > Editor > Code Style > CSV*). If you do so you will notice the actual purpose of the highlighting.

The functionality was indeed introduced in 1.7.0 by request (#30) and I personally think that it is a quite useful feature. Nevertheless, I agree that the coloring at the side/scrollbar is not really needed or wanted, but I couldn't find a way to get rid of it. Additionally I also noticed that the permanent highlighting of the values make them a bit less readable.

I am currently thinking about a way to keep this convenient feature in a way that it does not interfere with working on the CSV content. Suggestions are welcome! Most appealing to me is currently the behavior, that the column-hightlighting will only be enabled if something was selected in the current column.

**Comment by SeeSharpSoft** [comment]
Behavior change in v1.8.*: column highlighting only happens if user selects sth, e.g. double-click on a value or explicitly (see #44)

**Comment by magner58** [comment]
Hey @SeeSharpSoft , thanks for the explanation!

With v1.8 I think it works as expected: only selected column values are highlighted + selecting column value in diff view does not cause highlights on the side panel, thanks!

**Comment by SeeSharpSoft** [comment]
Great to hear - I consider this issue closed then.
