### ISSUE TITLE
Formatting works in 2.14.3 but not in latest 

### ISSUE THREAD

**Issue by ptahchiev** [SeeSharpSoft/intellij-csv-validator#472]
So i've been using an old IDEA and some old version of the plugin (2.14.3) and it was working great.
Now I had to update to a newer version of IDEA and the latest 3.2.0-231 version of the plugin and all of a sudden the formatting of the CSV stopped working.

This CSV:

```
MERGE io.nemesis.platform.core.entity.batch.StringCronjobParameterEntity,code[id]                              ,key                ,value         ,identifying[default=false;bool]
                                                                        ,full-type                             ,type               ,full          ,true
                                                                  ,b2c-site                              ,session.currentSite,backend-b2c   ,true
																		,indexName-resource                    ,indexName          ,resource      ,true

```

when I press Ctrl+Shift+F the IDEA is telling me everything is propelrly formatted:

![image](https://github.com/SeeSharpSoft/intellij-csv-validator/assets/5320045/d6ea8389-d61c-4d37-b897-01e0053e7690)

**Comment by automind-courses** [comment]
Hi,
We have the same problem.. Is it something new?

My PSV
```
testCase     |TFS  |task2care|delegate|preConditionsPublishUCPageBean
abc|33196|  |true    |xyz
abc|33196|CommitteeThresholdFirst|true    |xyz
abc|33234||true    |xyz
abc|33235||true    |xyz
abc|33198||true    |xyz
```

![image](https://github.com/SeeSharpSoft/intellij-csv-validator/assets/160175316/894a079b-3d28-4d4a-9ee9-2faa61f66a74)

**Comment by SeeSharpSoft** [comment]
New CSV Editor version 4.* is available, bringing back the tabularize formatting of version 2.*
