### ISSUE TITLE
It seems impossible to create a new line within a cell

### ISSUE THREAD

**Issue by shivam-enquero** [SeeSharpSoft/intellij-csv-validator#478]
Hi, new to this editor, not able to figure out how to add a new line within a cell.
Enter: moves to next cell
Shift+Enter: moves to above cell
Ctrl+Enter: nothing
Alt+Enter: moves to next cell
how is this simple operation so hard to figure out, pls help.

**Comment by SeeSharpSoft** [comment]
This are the key-bindings for the table editor: https://github.com/SeeSharpSoft/intellij-csv-validator#key-bindings

When I understand you correctly, you want to have an `Enter`/`Return` in the cell, which is `Ctrl+Enter`. I just tested it and it works for me, also the unit-tests are fine. Can you please double check. If it doesn't work for you, please provide more details like used IDE, version, CSV example if possible, used separator (e.g. comma, semicolon, tab) etc.
