### ISSUE TITLE
Treat fullwidth east asian characters as 2 characters wide in formatter

### ISSUE THREAD

**Issue by TJYSunset** [SeeSharpSoft/intellij-csv-validator#48]
## Expected
Format
```csv
汉字,lorem
ipsum,dolor
```
into
```csv
汉字 ,lorem
ipsum,dolor
```
How this should look like when a proper coding font with CJK support is used: 

![Example expected screenshot](https://user-images.githubusercontent.com/12986688/43075002-dbfcfdb8-8eb1-11e8-9a93-846295b36c4b.png)

## Actual
The example csv above will be formatted into
```csv
汉字   ,lorem
ipsum,dolor
```
screenshot:
![Example actual screenshot](https://user-images.githubusercontent.com/12986688/43075115-3fdc9848-8eb2-11e8-841b-9a5ae2f6b5bd.png)

## Cause
Fullwidth characters (examples including CJK Unified Ideograph "汉", Hiragana "あ", Fullwidth Form "Ａ", CJK Symbol/Punctuation "〄") are treated as halfwidth characters.

However, emojis like "😀" have their widths calculated properly.

## Solution
Use [ICU4J](http://site.icu-project.org) for finding fullwidth characters. See [this StackOverflow question](https://stackoverflow.com/questions/15114303/determine-whether-a-unicode-character-is-fullwidth-or-halfwidth-in-c).

I would have made a pull request, but the ******* ISP here won't let me download even a single gradle dependency without experiencing timeout.

## Notes
Like [the SO question's comment](https://stackoverflow.com/questions/15114303/determine-whether-a-unicode-character-is-fullwidth-or-halfwidth-in-c#comment-85436543) mentioned, super-wide glyphs besides CJK exists (what about this fish-like guy "௵"?). Might also be a related issue.

Some glyphs (like slanted quotes "“”") have different width in different fonts/locales. I have absolutely no idea how to handle this so no comment.

**Comment by SeeSharpSoft** [comment]
Short update: This really seems to be a bottomless pit with those double-wide and "super-wide" glyphs. And it actually is impossible to align them (always) 100% completely correct - their actual pixel-width is not (necessarly) twice of a monospace character.

Furthermore, the size of the suggested library is 11.8MB - which is IMO a far too big (size-wise) dependency for too little effect.

I am not sure yet how to tackle this best without blowing it out of proportion - ideas?

**Comment by TJYSunset** [comment]
Do not know about super-width glyphs... as for CJK (fullwidth alias "double width" glyphs):

> their actual pixel-width is not (necessarly) twice of a monospace character

Yes, like I said, the absolutely-double-width behavior is only apparent when "a proper coding font with CJK support is used". Using a correct font is end-users' responsibility.

And even if the text is misaligned, double width would be better than single width.

Example screenshots:

[SimSun](https://docs.microsoft.com/en-us/typography/font-list/simsun-extb), default font of IntelliJ IDEs on Simplified Chinese Windows. Not intended to be a coding font but happens to have monospaced latin 1 glyphs:

![simsun](https://user-images.githubusercontent.com/12986688/43373066-cf88f398-93d9-11e8-97f0-222ad177764c.png)

Misaligned combo, [Fira Code](https://github.com/tonsky/FiraCode) + [Noto Sans CJK SC](https://www.google.com/get/noto/help/cjk):

![firacode notosanscjksc](https://user-images.githubusercontent.com/12986688/43373092-eb96c98e-93d9-11e8-83c3-a3e274afdf67.png)

(OK I admit the above statement about misaligned text doesn't make much sense)

One carefully designed Japanese monospaced font, [M+ 1m](https://mplus-fonts.osdn.jp/about-en.html) (partially falled back to SimSun due to missing glyphs):

![mplus1m](https://user-images.githubusercontent.com/12986688/43373303-5cfae852-93db-11e8-9b50-96388fbbd750.png)

> the size of the suggested library is 11.8MB - which is IMO a far too big (size-wise) dependency for too little effect

Whoops, forgot to check out the dependency size...

The [EastAsianWidth.txt](https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt) from Unicode.org is only 169 KiB, and 21 KiB 
[after removing comments and stuff](https://github.com/SeeSharpSoft/intellij-csv-validator/files/2239406/EastAsianWidth.min.csv.txt).

**Comment by TJYSunset** [comment]
Also, by

> Some glyphs (like slanted quotes "“”") have different width in different fonts/locales

in the original issue, I mean the `A`(mbiguous) characters as defined in [UAX #11](https://www.unicode.org/reports/tr11/tr11-33.html#ED6). Now that I know they are defined in a standard, maybe just adding a switch for ambiguous widths is enough.

**Comment by SeeSharpSoft** [comment]
@TJYSunset Thanks! Based on all your input I have done a very basic implementation to tackle this issue. I will open a PR soon - I need to tackle the Ambiguous characters as well, currently I just treat them as narrow characters (as "when not in East Asian context"). Maybe it will just be a switch/setting as you mentioned.

FYI: I did some manual tests, and even with the SimSun font the results look just OK-ish but not perfect in the IDE:
![image](https://user-images.githubusercontent.com/3205800/43486297-c4f397ae-9513-11e8-9459-8265a164107f.png)
So I am definitely with you on that: 

> Using a correct font is end-users' responsibility.

**Comment by SeeSharpSoft** [comment]
East Asian full-width character support comes with Release 1.8.1

It needs to be enabled though in the codestyle settings, because the performance loss when enabled is noticable (for larger files): The time complexity to determine all column width for a CSV file increases from `O(k)` to `O(n * log n)` (with `k` being the total number of 'cells' and `n` the total number of characters (so `k <= n`)) when enabled.

Please note that this option is only relevant to tabularize the CSV.
