### ISSUE TITLE
TSV file support

### ISSUE THREAD

**Issue by tyerq** [SeeSharpSoft/intellij-csv-validator#5]
I like the file formatting and syntax highlighting, but most of my files are ".tsv" (tab as separator)
Is it possible to get it working with TSV files also?

**Comment by SeeSharpSoft** [comment]
Yes, its definitely possible - I have a local feature branch (I can push it to share the state). Syntax highlighting and validation works fine.
The issue with tabs is the formatting when adding or removing spaces. This is currently not handled correctly, the tabs are removed after formatting. I didn't take the time to investigate further yet.

**Comment by SeeSharpSoft** [comment]
feature branch to support tabs as separator: https://github.com/SeeSharpSoft/intellij-csv-validator/tree/fb_tab_separator

**Comment by SeeSharpSoft** [comment]
Part of [Release 1.6.1](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.6.1)
