### ISSUE TITLE
Columns starting with =" cause validation error

### ISSUE THREAD

**Issue by joaonc** [SeeSharpSoft/intellij-csv-validator#53]
I frequently need to edit the CSV files in Excel and for long numbers, ex `6006499647128636419`, these show in Excel as `6.0065E+18`.

In order to force Excel to interpret those numbers as text, the easiest way is to have them as `="6006499647128636419"`.  Another way is to import the data in _Excel → Data → Get external data_, but that's too hard..   (more details [here](https://superuser.com/questions/307496/how-can-i-set-excel-to-always-import-all-columns-of-csv-files-as-text)).

However, when I set the value as `="6006499647128636419"` (with `="`), there's a validation error in PyCharm (I imagine the same thing will happen in IntelliJ).

Could this be fixed and allow for `="<value>"` entries?

**Comment by SeeSharpSoft** [comment]
`="<value>"` is actually an incorrect CSV value. The correct writing is `"=""<value>"""`. I would introduce a bug if it would be "fixed". Allowing incorrect syntax for the purpose of mitigating flaws or special CSV handling of other tools is nothing I'd like to support.

In Jetbrains IDEs you can mark single files to be treated as plain text not to be bothered by syntax highlighting/validation: Right click in the project inspector the corresponding file and then select `Mark as Plain Text` in the context menu. The drawback: This disables all other language features as well...

**Comment by joaonc** [comment]
Bummer..   I agree that adding special handling that are not format standard opens another set of issues, potentially worse...   Tx for the quick reply!
