### ISSUE TITLE
Multi-line quoted string with empty line causes IDEA error

### ISSUE THREAD

**Issue by MarkJeronimus** [SeeSharpSoft/intellij-csv-validator#54]
When a CSV file contains a single string-quote `"` on a line ~~and is missing the closing quote~~, and if there are multiple lines below, none of which contain a string-quote, the entire rest of the CSV file becomes a multi-line string field according to the syntax highlighter. When that happens, IDEA gives an error in the lower right corner. I'm posting it here so you can figure out if the bug lies with the plugin or with IDEA.

> java.lang.Throwable: Invalid range specified: (-2147483648, 1); 
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
> 	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:233)
> 	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:228)
> 	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:224)
> 	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
> 	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
> 	at com.intellij.codeInspection.longLine.LongLineInspection$2.visitElement(LongLineInspection.java:110)
> ...

**Comment by SeeSharpSoft** [comment]
@MarkJeronimus Thanks for sharing, but I cannot reproduce it:
![image](https://user-images.githubusercontent.com/3205800/45760650-df8ce000-bc2a-11e8-9247-1fc36f77a200.png)

It is a valid syntax, IDEA does not show any error - all looks good. Or did I miss something?

It would be helpful if you could share a sample file when this happens in your IDE, and provide some additional information like which IDEA (IntelliJ, PhpStorm, PyCharm etc.) and version. Thanks!

**Comment by MarkJeronimus** [comment]
It seems to only happen when there's an empty line in the string.
Example (tested as both csv and tsv):

    A
    
    B

Then type a quote before `A`.

**Comment by SeeSharpSoft** [comment]
This seems to be an issue with the EAP: https://youtrack.jetbrains.com/issue/WI-43536

**Comment by SeeSharpSoft** [comment]
Feel free to re-open issue if error still appears

**Comment by MarkJeronimus** [comment]
It was fixed in IntelliJ EAP last week.
