### ISSUE TITLE
Visible tabs in TSV

### ISSUE THREAD

**Issue by MarkJeronimus** [SeeSharpSoft/intellij-csv-validator#55]
It would be useful to have visible tabs (but not spaces). I now use a different background for the 'separator' character, but this background disappears for the current line, making it look awkward and eyeballing the correctness of a line requires you to move the cursor to another line.

![tsv-invisible-tabs](https://user-images.githubusercontent.com/5273753/45804113-8caf3900-bcbb-11e8-8fb7-4b3eddaca317.png)

**Comment by SeeSharpSoft** [comment]
@MarkJeronimus Yes, changing the background of the separator is the actual way to go for tab coloring. You can disable the background coloring of the current row in general here:
![image](https://user-images.githubusercontent.com/3205800/45830224-f56ad580-bcfc-11e8-9b5f-732fb74735f7.png)


I will add the possibility to change/deactivate the coloring of the current row for CSV/TSV files only - I couldn't find a way to change the priority of the different color options.


**Please note:** You can enable displaying whitespace character (which includes tabs) via the settings as well:
![image](https://user-images.githubusercontent.com/3205800/45830084-a755d200-bcfc-11e8-913f-fca1b224e9b6.png)

**Comment by SeeSharpSoft** [comment]
Update: Unfortunately is changing the caret-row-color language specific not as simple as I thought it would be... I will dig into alternative solutions.

**Comment by SeeSharpSoft** [comment]
#59 introduces a CSV editor with custom setting capabilities including explicit TAB (separator) highlighting and caret-row highlight switch

**Comment by SeeSharpSoft** [comment]
[Release 1.9.0](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.9.0) includes an exclusive TAB separator highlighter that has a higher priority than the caret-row-highlighting and can be defined separately from the standard separator highlight color.
