### ISSUE TITLE
Double quotes break tooltips and colouring

### ISSUE THREAD

**Issue by egoisticalgoat** [SeeSharpSoft/intellij-csv-validator#60]
When you have double quotation marks in the middle of a field, they give the error `CvsTokenType.CRLF or CsvTokenType.TEXT expected, got '"'`. After that, all following fields and rows are broken and count as that one row/field.
![image](https://user-images.githubusercontent.com/18332886/45941234-7d8efa80-bfdd-11e8-9660-0a04738378b1.png)
([example.tsv](https://github.com/SeeSharpSoft/intellij-csv-validator/files/2409987/example.txt))

**Comment by SeeSharpSoft** [comment]
"When you have double quotation marks in the middle of a field" ... then the field needs to start and end with double quotation marks and the actual/inner double quotation marks needs to be escaped with a double quotation mark. (see [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt))

In [Wikipedia (date: 2018/9/24)](https://en.wikipedia.org/wiki/Comma-separated_values) it is described as follows:

> Fields with embedded commas or double-quote characters must be quoted.

> Each of the embedded double-quote characters must be represented by a pair of double-quote characters.

**Comment by SeeSharpSoft** [comment]
I consider this resolved...

PS: The plugin provides the CSV inspection "Surround with quotes" (Alt+Enter on erroneous position) that can help to quickly fix those issues.
