### ISSUE TITLE
Please provide change logs

### ISSUE THREAD

**Issue by JThoennes** [SeeSharpSoft/intellij-csv-validator#61]
Hello and thanks for this plugin!
I had some trouble to find an overview about the lates changes (change log).
Would be nice to see this prominently on your page and even in the IntelliJ plugin update dialog.
Many thanks, Jörg

**Comment by SeeSharpSoft** [comment]
I copied over the whole changelog from https://plugins.jetbrains.com/plugin/10037-csv-plugin to a file within the repository for good karma.

@JThoennes The [Jetbrains plugin repository](https://plugins.jetbrains.com/) is actually the place where you find the changelog of plugins - and those changelog texts are the ones that also appear in the IntelliJ plugin update dialog automatically. It was already and always there...
