### ISSUE TITLE
Can't place caret on bottom row using mouse

### ISSUE THREAD

**Issue by MarkJeronimus** [SeeSharpSoft/intellij-csv-validator#62]
When the file has more lines than fit in the window, aiming the mouse at the bottom row almost immediately (in ~0.25s) pops up a message box, preventing you from clicking on the text to move the caret there. It's really hard to move the mouse cursor over the text and clicking before it pops up.

![tsv-annoying-popup](https://user-images.githubusercontent.com/5273753/46278618-f30f4380-c566-11e8-9cd0-3b38eaefd9de.png)

**Comment by MarkJeronimus** [comment]
Excuse me, it seems to be a new IntellIJ bug. https://youtrack.jetbrains.com/issue/IDEA-199744

**Comment by SeeSharpSoft** [comment]
Thx for the update - I actually can't reproduce the described behavior with the latest IntelliJ IDE 2018.2.4

**Comment by SeeSharpSoft** [comment]
I included an option in [Release 1.9.0](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.9.0) to disable the balloon info - which can be helpful to prevent those or similar unwanted situations in future and also improves performance for very large files slightly. However, this is independent of the pending Jetbrains issue.
