### ISSUE TITLE
PyCharm - CSV "Tabularize" formatting has no effect

### ISSUE THREAD

**Issue by obarak** [SeeSharpSoft/intellij-csv-validator#7]
Maybe I'm missing something, but using **PyCharm 2017.3.3** and **CSV Plugin 1.4.1**, I can't make CSV files appear tabularized when I open them, regardless of the setting under Code Style-->CSV.

**Comment by obarak** [comment]
Thanks, got it! I thought the formatting was display-only, and now I realize it actually changes the file (e.g. adds whitespaces) which would require me to handle this when processing it. Is there any way to actually make such formatting display-only?

**Comment by SeeSharpSoft** [comment]
Unfortunately I don’t see better way to separate display & edit than having a separate display “editor” as it is done in the Ultimate edition/PhPStorm/DataGrip/... - there is already some kind of discussion here #2. Contributions are always welcome but I myself have currently not planned to (re-)implement it.
