### ISSUE TITLE
Line number feature is gone

### ISSUE THREAD

**Issue by klapaudius** [SeeSharpSoft/intellij-csv-validator#72]
Hello,

In the new version the line number is gone.
It was very useful when you need to go back in text mode to duplicate a line
BTW Thanks for your plugin.

**Comment by SeeSharpSoft** [comment]
@klapaudius Do you mean line numbers in the table editor tab? The table editor is a brand new feature of version CSV Plugin version 2.*, pls do not mix it up with the "Edit as Table..." functionality. Line numbers are not implemented yet - they would actually be a new feature.
