### ISSUE TITLE
Table Editor Headers

### ISSUE THREAD

**Issue by Sauerbier** [SeeSharpSoft/intellij-csv-validator#73]
It would be nice if the Table-Editor's header (A,B,C,D...) would be replaced with the actual csv header

**Comment by SeeSharpSoft** [comment]
Two challanges here:

- The header is optional
- And even the header has to be editable

How to tackle this best?

**Comment by Sauerbier** [comment]
My idea would be to:

1. Add a checkBox (either in the settings or next to the "Textlines per row") to choose whether or not to use the csv's header as the table header

2. (If 1. is checked) make the table header editable. I would try to do it myself but I don't have a lot of freetime currently. But I found an article on how to do this if anyone wants to give it a try, click [here](http://esus.com/creating-a-jtable-with-editable-headers/)

**Comment by SeeSharpSoft** [comment]
Having a checkbox for fixing the header also came to my mind - and I like that idea. 👍 As it needs to be file specific, it should become an option of the table editor itself.

Regarding the editable header: I had a quick look at the code (@Sauerbier thanks for providing the link!) and it seems that header editing is only working if column re-ordering is disabled - which is a feature I definitely want to keep enabled at all times. I would need more time to investigate a little bit further to get a better understanding of the implications.

However, I think that having only the checkbox "Fixed header row" is all it needs: While checked, the header row is just that - fixed and not changeable. To change a header value, just uncheck, do the change, check again. In my experience, changing a header value happens only once in a while and most of the time it should stay just fixed.
