### ISSUE TITLE
Window cannot be resized

### ISSUE THREAD

**Issue by MakotoE** [SeeSharpSoft/intellij-csv-validator#75]
When I split a window and open a csv file with CSV Editor on the right pane, I can't make the CSV Editor pane smaller. I can make the pane larger however. I am using GoLand on Debian.

This is what the editor looks like when I am unable to resize the pane.
![CSV Editor](https://user-images.githubusercontent.com/36318069/49421170-a18c5c00-f743-11e8-87bd-433371e4a6a1.png)

**Comment by MakotoE** [comment]
Sorry if you need the plug-in's version number; I can't seem to find it in the IDE.

**Comment by nicholascloud** [comment]
Having this same problem in WebStorm.

WebStorm 2018.3
Build #WS-183.4284.130, built on November 19, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
CSV Plugin v2.0.1

**Comment by Hamza141** [comment]
If you switch to the Table Editor view and close the popup (pictured below), you'll be able to resize the window. Once I had to reopen the file for the popup the to show up

![image](https://user-images.githubusercontent.com/14940503/49479617-a7d91180-f7f1-11e8-9842-191cc1cec32f.png)

**Comment by SeeSharpSoft** [comment]
Thanks all for reporting! It is indeed an issue due to using non-scrollable grid layout - will be fixed in upcoming release.

**Comment by MarkJeronimus** [comment]
Editor panel has a minimumSize of exactly 1024x100
