### ISSUE TITLE
Foreground color change

### ISSUE THREAD

**Issue by tomasberdych** [SeeSharpSoft/intellij-csv-validator#84]
Hi. I can't change foreground color for CSV file in Settings/Editor/Color Scheme/CSV. Only background color is allowed for change. Scheme is "Darcula". Any "untick inherited" for column 1-10. Help me please. Tom.

**Comment by SeeSharpSoft** [comment]
The feature of changing all kind of text-attributes for column highlighting will be part of release 2.1.0 (#83)

**Comment by tomasberdych** [comment]
Wow. Thank you very match.

**Comment by SeeSharpSoft** [comment]
Released in with version 2.1.0
