### ISSUE TITLE
Fails to tabulate a very simple TSV file; still fails even when I specify the separator

### ISSUE THREAD

**Issue by burnchar** [SeeSharpSoft/intellij-csv-validator#865]
This plugin fails to detect the following very simple TSV as tab-separated:

```VERB_IND	VERB	VERB_DESC
0	VAL1	Some space separated text
1	VAL2	More space separated text
2	Some other val	More space separated text
3	Another space-sep val	More space separated text
```

![image](https://github.com/user-attachments/assets/c4d89b50-dd63-49c2-8c3d-a9037db5d024)

When I explicitly configure the plugin to use only a TAB, it still can't figure out the file:

![image](https://github.com/user-attachments/assets/9202f8e5-3817-4f2b-9b2c-d3ef14adfb19)

Using the latest Rider and plugin as of August 21, 2024.

**Comment by SeeSharpSoft** [comment]
When creating a new CSV file, the default value separator is used and associated with the file. Changing the settings afterwards is having no effect. Instead, use the editor context menu to set the value separator for that file.

**Comment by SeeSharpSoft** [comment]
Tested given example and it is parsed correctly - try [setting the value separator](https://github.com/SeeSharpSoft/intellij-csv-validator?tab=readme-ov-file#file-specific-value-separator--escape-character) for the file in question.
