### ISSUE TITLE
new version 4.0.0 removes all spaces upon formatting

### ISSUE THREAD

**Issue by automind-courses** [SeeSharpSoft/intellij-csv-validator#880]
Due an issue 472 - i've upgraded to IntelliJ 242 and version 4.0 of this GR8 plugin :)
In the issue 472 - there was no effect for formatting

now my CSV (PSV in my case) looks like:

![image](https://github.com/user-attachments/assets/83ad4c4d-d675-4ab0-99be-8e4bfe6f32bb)

but after update, formatting (Ctrl+Alt+L) - removes **all of spaces** from PSV

![image](https://github.com/user-attachments/assets/2c6c9200-347d-47e3-a3ae-22c1b1f89fe2)

**Comment by SeeSharpSoft** [comment]
@automind-courses In version 4.0, [Tabularize](https://github.com/SeeSharpSoft/intellij-csv-validator?tab=readme-ov-file#tabularize) is not enabled by default but must be activated explicitly in the settings.

**Comment by automind-courses** [comment]
TNX.
