### ISSUE TITLE
Escaped quotes

### ISSUE THREAD

**Issue by MattTuttle** [SeeSharpSoft/intellij-csv-validator#9]
Escaped quotes produce a syntax error with this plugin.

```
0,"Hello \"World\"!",1
```

**Comment by SeeSharpSoft** [comment]
It is actually a syntax error. Quotes are escaped with another double quote upfront in CSV ([RFC-4180](https://tools.ietf.org/html/rfc4180)).

In the provided example, `“Hello \”` is (already) a field (see RFC), as well as `World\` and `“!”`. And fields needs to be separated by a comma. So the correct syntax for the given example is:

```
0,”Hello “”World””!”,1
```

**Comment by MattTuttle** [comment]
Good to know. Thanks!
