### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by DylanMunyard** [SeeSharpSoft/intellij-csv-validator#96]
Hi - since taking the new table editor version of your plug in I can't load up a CSV with around 2400 rows, about 20 columns, file size 364KB and be able to edit the file. It's very laggy to click anywhere in the file. What I liked about your previous version was column highlighting by selecting a row value. 

Do you expect there is performance impacts on a file this large, I'm using this inside Rider and have used your plugin for quite some time, this new version means I've had to disable the plugin.

**Comment by SeeSharpSoft** [comment]
@DylanMunyard I am sorry to hear that. I actually cannot reproduce it yet, but haven't tested it in Inside Rider (will do it when I got some time).

One of my test-files is [this](http://samplecsvs.s3.amazonaws.com/SacramentocrimeJanuary2006.csv) one (linked on this [page](https://support.spatialkey.com/spatialkey-sample-csv-data/) (last entry)), which is roughly twice the size of your file and does not cause any problems. Though it might be related to the number of columns - that I have to investigate in. Could you meanwhile give it a try and open the linked file to check whether you encounter performance issues? Thanks.

Additionally, you could also disable all (or partial) performance relevant features:
![image](https://user-images.githubusercontent.com/3205800/51585527-f80f4e80-1ed9-11e9-9fb1-d25e9f12dfdd.png)

Do you still have issues? If not, can you narrow it down to a setting? (Btw: Are you using the code formatting? Also a potential candidate for performance issues (but only when executed)).

*If any other user have similar experience, please post it in this thread with some details about the used settings and the file. Provide an example if possible.*

PS: 

> What I liked about your previous version was column highlighting by selecting a row value.

This feature is still in.

**Comment by DylanMunyard** [comment]
Hi @SeeSharpSoft thanks for the reply and pointing out those settings. So what I'll have to do is wait until work Monday as I'm loading your file OK now as well as the original files but I don't have my usual work load of a couple of Rider sessions open. When it does happen I'll work through each of the settings and report back which if any make a difference. Also worth noting is I really like how your plugin works in the default VCS merge tool, so if you make an edit then compare it with the remote branch that's where I have these issues, especially around not being able to highlight the column.

I'll pay more attention if this happens and add more details to this issue.
