### ISSUE TITLE
Table Editor: Trailing spaces get lost

### ISSUE THREAD

**Issue by thevictor13** [SeeSharpSoft/intellij-csv-validator#99]
First of all thank you for the plugin, the new table editor will come super handy.

We are using TSV files without text delimiters, value separators are TABs of course. However upon opening the editor tab, any trailing spaces get lost. regardless of settings. The file is immediately in a changed state once the Table Editor tab is opened.

Again, thank you for your efforts!

**Comment by SeeSharpSoft** [comment]
@thevictor13 Thanks for your feedback!

This behavior is actually intended/natural: Leading/Trailing spaces are ignored if the value is not surrounded by double-quotes - they are assumed to be just white-space characters and not part of the value itself. To enforce keeping the white-spaces (by making it part of the value), the values should be surrounded by doubles-quotes (e.g. by using the "Quote All" intention (Alt+Enter) in CSV/TSV text editor).

**Comment by SeeSharpSoft** [comment]
Works as intended: spaces within double-quotes are respected, surrounding white-spaces outside double-quotes (or leading/trailing non-quoted values) are considered to be used for text-formatting only.
